### PR TITLE
Add support to SystemJS config map. Closes #185.

### LINKED ISSUE #185: Add support for SystemJS map configuration
Use case:

I want to be able to change the mapping for electron while testing. By extending `karma-jspm` to support the SystemJS config `map` object, I will be able to do the following:

**karma.conf.js:**
```
    ...

    jspm: {
      map: {
        'electron': '@empty'
      }
    },

    ...
```

### PR DESCRIPTION
**Pull request by dougludlow**

### CODE REVIEW

**Comment by SerkanSipahi** [comment]
@dougludlow support for SystemJS config map is under version 2.2.2 available.
@computmaxer please deploy 2.2.2 on npm, thanx.

**Comment by dougludlow** [comment]
@SerkanSipahi Thanks! 👍

**Comment by computmaxer** [comment]
@SerkanSipahi the package.json wasn't updated to reflect the new version for the tag. I'll fix it. Also I'll look into adding you as a publisher

**Comment by computmaxer** [comment]
@SerkanSipahi do you have an account on npmjs.org?

**Comment by SerkanSipahi** [comment]
@computmaxer https://www.npmjs.com/~bitcollage

**Comment by maxwellpeterson-wf** [comment]
@SerkanSipahi you should have publish rights on `npm` now.

**Comment by SerkanSipahi** [comment]
@maxwellpeterson-wf thank you...

**Pull request merged**
