### PR TITLE
CP-2040 Release karma-jspm 2.2.1

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-2040

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= karma-jspm 2.2.1 items =======

 CP-2409  - Update glob dependency  - https://github.com/Workiva/karma-jspm/pull/173

======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.2.0...CP-2040_release_2.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/karma-jspm/compare/2.2.0...2.2.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Pull request closed without merging**
